//#382
export const FirstSome={
    	some_1: {type: 'BOOL',db: 3,dbb: 0,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_2: {type: 'BOOL',db: 3,dbb: 0,bit: 1,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	som6: {type: 'BOOL',db: 3,dbb: 0,bit: 2,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	som5: {type: 'BOOL',db: 3,dbb: 0,bit: 3,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	som4: {type: 'BOOL',db: 3,dbb: 0,bit: 4,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	som3: {type: 'BOOL',db: 3,dbb: 0,bit: 5,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	som2: {type: 'BOOL',db: 3,dbb: 0,bit: 6,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_3: {type: 'BOOL',db: 3,dbb: 0,bit: 7,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_Int_1: {type: 'INT',db: 3,dbb: 2,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_0: {type: 'BOOL',db: 3,dbb: 4,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_byte_1: {type: 'BYTE',db: 3,dbb: 5,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit: {type: 'BOOL',db: 3,dbb: 6,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_real: {type: 'REAL',db: 3,dbb: 8,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_1: {type: 'BOOL',db: 3,dbb: 12,bit: 0,desc: 'some 1',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_real_2: {type: 'REAL',db: 3,dbb: 14,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_3: {type: 'BOOL',db: 3,dbb: 18,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_int: {type: 'INT',db: 3,dbb: 20,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	wasyl: {	some_1: {type: 'BOOL',db: 3,dbb: 22,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	int_1: {type: 'INT',db: 3,dbb: 24,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	bool_End: {type: 'BOOL',db: 3,dbb: 26,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some: {type: 'BOOL',db: 3,dbb: 26,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some2: {type: 'BOOL',db: 3,dbb: 26,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some3: {type: 'BOOL',db: 3,dbb: 26,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some4: {type: 'BOOL',db: 3,dbb: 26,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some5: {type: 'BOOL',db: 3,dbb: 26,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some6: {type: 'BOOL',db: 3,dbb: 26,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some7: {type: 'BOOL',db: 3,dbb: 26,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some8: {type: 'BOOL',db: 3,dbb: 27,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	some9: {type: 'BOOL',db: 3,dbb: 27,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	some_4: {type: 'BOOL',db: 3,dbb: 28,bit: 2,desc: 'some 3',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	Other_Real: {type: 'REAL',db: 3,dbb: 30,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_arr: {type: 'BYTE',db: 3,dbb: 34,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bool_2: {type: 'BOOL',db: 3,dbb: 35,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_other_arr: {type: 'INT',db: 3,dbb: 36,bit: 0,desc: 'tekst some',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_9_bool: {type: 'BOOL',db: 3,dbb: 38,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	other_Struct: {	one: {type: 'BOOL',db: 3,dbb: 40,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	two: {type: 'BOOL',db: 3,dbb: 40,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	three: {type: 'BOOL',db: 3,dbb: 40,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	some_other: {type: 'BOOL',db: 3,dbb: 42,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	r1: {type: 'BOOL',db: 3,dbb: 42,bit: 1,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bool_4: {type: 'BOOL',db: 3,dbb: 42,bit: 2,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_robert: {type: 'BOOL',db: 3,dbb: 42,bit: 3,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	other: {type: 'BOOL',db: 3,dbb: 42,bit: 4,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_Struct: {	rob: {type: 'BOOL',db: 3,dbb: 44,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	dipper_Struct: {	littleOne: {type: 'BOOL',db: 3,dbb: 46,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
	litttleTwo: {type: 'INT',db: 3,dbb: 48,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
}
},
	addidas: {type: 'BOOL',db: 3,dbb: 50,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	kot_1: {	item_1: {type: 'BOOL',db: 3,dbb: 52,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	item_2: {type: 'BOOL',db: 3,dbb: 52,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	byte_1: {type: 'BYTE',db: 3,dbb: 54,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_2: {type: 'BOOL',db: 3,dbb: 55,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_byte: {type: 'BYTE',db: 3,dbb: 56,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_other_bit: {type: 'BOOL',db: 3,dbb: 57,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	char_1: {type: 'CHAR',db: 3,dbb: 58,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	bool_one: {type: 'BOOL',db: 3,dbb: 59,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	int_44: {type: 'INT',db: 3,dbb: 60,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sbool: {type: 'BOOL',db: 3,dbb: 62,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sReal: {type: 'REAL',db: 3,dbb: 64,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	ssbool: {type: 'BOOL',db: 3,dbb: 68,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	ssInt: {type: 'INT',db: 3,dbb: 70,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sssbool: {type: 'BOOL',db: 3,dbb: 72,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sssByte: {type: 'BYTE',db: 3,dbb: 73,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sssReal: {type: 'REAL',db: 3,dbb: 74,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	arr_big: {type: 'BYTE',db: 3,dbb: 78,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	new_bool: {type: 'BOOL',db: 3,dbb: 79,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	lastStruct: {	bool1: {type: 'INT',db: 3,dbb: 80,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	bool2: {type: 'BOOL',db: 3,dbb: 82,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	bool3: {type: 'BOOL',db: 3,dbb: 82,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	bool4: {type: 'BOOL',db: 3,dbb: 82,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	d1: {type: 'BOOL',db: 3,dbb: 82,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	d2: {type: 'BOOL',db: 3,dbb: 82,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	d3: {type: 'BOOL',db: 3,dbb: 82,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	d4: {type: 'BOOL',db: 3,dbb: 82,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	d5: {type: 'BOOL',db: 3,dbb: 82,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	newInt: {type: 'INT',db: 3,dbb: 84,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined}
}