//#382
export const HmiStatsPendolino={
    	HMI_IN: {	Reserwa_0_10: {type: 'BOOL',db: 129,dbb: 0,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_11: {type: 'BOOL',db: 129,dbb: 0,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_12: {type: 'BOOL',db: 129,dbb: 0,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_13: {type: 'BOOL',db: 129,dbb: 0,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_14: {type: 'BOOL',db: 129,dbb: 0,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_15: {type: 'BOOL',db: 129,dbb: 0,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_16: {type: 'BOOL',db: 129,dbb: 0,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_17: {type: 'BOOL',db: 129,dbb: 0,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_18: {type: 'BOOL',db: 129,dbb: 1,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_19: {type: 'BOOL',db: 129,dbb: 1,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_110: {type: 'BOOL',db: 129,dbb: 1,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_111: {type: 'BOOL',db: 129,dbb: 1,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_112: {type: 'BOOL',db: 129,dbb: 1,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_113: {type: 'BOOL',db: 129,dbb: 1,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_114: {type: 'BOOL',db: 129,dbb: 1,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_115: {type: 'BOOL',db: 129,dbb: 1,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_116: {type: 'BOOL',db: 129,dbb: 2,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_117: {type: 'BOOL',db: 129,dbb: 2,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_118: {type: 'BOOL',db: 129,dbb: 2,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_119: {type: 'BOOL',db: 129,dbb: 2,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_120: {type: 'BOOL',db: 129,dbb: 2,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_121: {type: 'BOOL',db: 129,dbb: 2,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_122: {type: 'BOOL',db: 129,dbb: 2,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_123: {type: 'BOOL',db: 129,dbb: 2,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_124: {type: 'BOOL',db: 129,dbb: 3,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_125: {type: 'BOOL',db: 129,dbb: 3,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_126: {type: 'BOOL',db: 129,dbb: 3,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_127: {type: 'BOOL',db: 129,dbb: 3,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_128: {type: 'BOOL',db: 129,dbb: 3,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_129: {type: 'BOOL',db: 129,dbb: 3,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_130: {type: 'BOOL',db: 129,dbb: 3,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_131: {type: 'BOOL',db: 129,dbb: 3,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_0_132: {type: 'BOOL',db: 129,dbb: 4,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_KB1: {type: 'DINT',db: 129,dbb: 6,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_KB2: {type: 'DINT',db: 129,dbb: 10,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_I1: {type: 'DINT',db: 129,dbb: 14,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_I2: {type: 'DINT',db: 129,dbb: 18,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_I3: {type: 'DINT',db: 129,dbb: 22,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_Gender: {type: 'DINT',db: 129,dbb: 26,bit: 0,desc: 'Wartosc licznika palet przewiezionych na Gender',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_O1: {type: 'DINT',db: 129,dbb: 30,bit: 0,desc: 'Wartosc palet odebranych przez odbieranie',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	War_Licz_Palet_Reserwa: {type: 'DINT',db: 129,dbb: 34,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Przejechane_KM: {type: 'REAL',db: 129,dbb: 38,bit: 0,desc: 'Wartosc Km do(0.1KM) ile przejechal wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Pomoc_Kilometry: {type: 'DINT',db: 129,dbb: 42,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Posuw_licznikow: {type: 'INT',db: 129,dbb: 46,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
Tablica_IN_INT: [
 {type: 'INT',db: 129,dbb: 48,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 50,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 52,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 54,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 56,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 58,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
 ],
Tablica_IN_DWORD: [
 {type: 'DINT',db: 129,dbb: 60,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 64,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 68,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 72,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 76,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 80,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 84,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DINT',db: 129,dbb: 88,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
 ],
	Aktualna_Data: {type: 'DATE_AND_TIME',db: 129,dbb: 92,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	HMI_OUT: {	Wyzw_licznikow: {type: 'BOOL',db: 129,dbb: 100,bit: 0,desc: 'wyzwolenie wyswietlania licznikow',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_01: {type: 'BOOL',db: 129,dbb: 100,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_02: {type: 'BOOL',db: 129,dbb: 100,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_03: {type: 'BOOL',db: 129,dbb: 100,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_04: {type: 'BOOL',db: 129,dbb: 100,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_05: {type: 'BOOL',db: 129,dbb: 100,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_06: {type: 'BOOL',db: 129,dbb: 100,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_07: {type: 'BOOL',db: 129,dbb: 100,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_08: {type: 'BOOL',db: 129,dbb: 101,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_09: {type: 'BOOL',db: 129,dbb: 101,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_010: {type: 'BOOL',db: 129,dbb: 101,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_011: {type: 'BOOL',db: 129,dbb: 101,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_012: {type: 'BOOL',db: 129,dbb: 101,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_013: {type: 'BOOL',db: 129,dbb: 101,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_014: {type: 'BOOL',db: 129,dbb: 101,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_015: {type: 'BOOL',db: 129,dbb: 101,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_016: {type: 'BOOL',db: 129,dbb: 102,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_017: {type: 'BOOL',db: 129,dbb: 102,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_018: {type: 'BOOL',db: 129,dbb: 102,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_019: {type: 'BOOL',db: 129,dbb: 102,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_020: {type: 'BOOL',db: 129,dbb: 102,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_021: {type: 'BOOL',db: 129,dbb: 102,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_022: {type: 'BOOL',db: 129,dbb: 102,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_023: {type: 'BOOL',db: 129,dbb: 102,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_024: {type: 'BOOL',db: 129,dbb: 103,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_025: {type: 'BOOL',db: 129,dbb: 103,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_026: {type: 'BOOL',db: 129,dbb: 103,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_027: {type: 'BOOL',db: 129,dbb: 103,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_028: {type: 'BOOL',db: 129,dbb: 103,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_029: {type: 'BOOL',db: 129,dbb: 103,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_030: {type: 'BOOL',db: 129,dbb: 103,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_031: {type: 'BOOL',db: 129,dbb: 103,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_032: {type: 'BOOL',db: 129,dbb: 104,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_033: {type: 'DINT',db: 129,dbb: 106,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_034: {type: 'DINT',db: 129,dbb: 110,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_035: {type: 'DINT',db: 129,dbb: 114,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_036: {type: 'DINT',db: 129,dbb: 118,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_037: {type: 'DINT',db: 129,dbb: 122,bit: 0,desc: 'Wartosc licznika palet przewiezionych przez wozek',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_038: {type: 'DINT',db: 129,dbb: 126,bit: 0,desc: 'Wartosc licznika palet przewiezionych na Gender',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_039: {type: 'DINT',db: 129,dbb: 130,bit: 0,desc: 'Wartosc palet odebranych przez odbieranie',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_100_040: {type: 'DINT',db: 129,dbb: 134,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
Tablica_OUT_INT: [
 {type: 'INT',db: 129,dbb: 138,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 140,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 142,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 144,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 146,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 148,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 150,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 152,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 154,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
 ],
Tablica_OUT_DWORD: [
 {type: 'DWORD',db: 129,dbb: 156,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 160,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 164,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 168,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 172,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 176,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 180,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 184,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
 ],
	Reserwa_DWORD: {type: 'DWORD',db: 129,dbb: 188,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Aktualna_Data: {type: 'DATE_AND_TIME',db: 129,dbb: 192,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	HMI_IN_OUT: {	Reserwa_200_0: {type: 'BOOL',db: 129,dbb: 200,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_1: {type: 'BOOL',db: 129,dbb: 200,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_11: {type: 'BOOL',db: 129,dbb: 200,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_12: {type: 'BOOL',db: 129,dbb: 200,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_13: {type: 'BOOL',db: 129,dbb: 200,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_14: {type: 'BOOL',db: 129,dbb: 200,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_15: {type: 'BOOL',db: 129,dbb: 200,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_16: {type: 'BOOL',db: 129,dbb: 200,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_17: {type: 'BOOL',db: 129,dbb: 201,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_18: {type: 'BOOL',db: 129,dbb: 201,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_19: {type: 'BOOL',db: 129,dbb: 201,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_110: {type: 'BOOL',db: 129,dbb: 201,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_111: {type: 'BOOL',db: 129,dbb: 201,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_112: {type: 'BOOL',db: 129,dbb: 201,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_113: {type: 'BOOL',db: 129,dbb: 201,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_114: {type: 'BOOL',db: 129,dbb: 201,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_115: {type: 'BOOL',db: 129,dbb: 202,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_116: {type: 'BOOL',db: 129,dbb: 202,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_117: {type: 'BOOL',db: 129,dbb: 202,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_118: {type: 'BOOL',db: 129,dbb: 202,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_119: {type: 'BOOL',db: 129,dbb: 202,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_120: {type: 'BOOL',db: 129,dbb: 202,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_121: {type: 'BOOL',db: 129,dbb: 202,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_122: {type: 'BOOL',db: 129,dbb: 202,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_123: {type: 'BOOL',db: 129,dbb: 203,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_124: {type: 'BOOL',db: 129,dbb: 203,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_125: {type: 'BOOL',db: 129,dbb: 203,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_126: {type: 'BOOL',db: 129,dbb: 203,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_127: {type: 'BOOL',db: 129,dbb: 203,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_128: {type: 'BOOL',db: 129,dbb: 203,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_129: {type: 'BOOL',db: 129,dbb: 203,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_130: {type: 'BOOL',db: 129,dbb: 203,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	Reserwa_200_131: {type: 'BOOL',db: 129,dbb: 204,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
Tablica_IN_OUT_INT: [
 {type: 'INT',db: 129,dbb: 206,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 208,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 210,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 212,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 214,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 216,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 218,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 220,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 222,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 224,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 226,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 228,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 230,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 232,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 234,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 236,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 238,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 240,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 242,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 244,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 246,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 248,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 250,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 252,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 129,dbb: 254,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
 ],
Tablica_IN_OUT_DWORD: [
 {type: 'DWORD',db: 129,dbb: 256,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 260,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 264,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 268,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 272,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 276,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 280,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 284,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'DWORD',db: 129,dbb: 288,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
 ],
	Aktualna_Data: {type: 'DATE_AND_TIME',db: 129,dbb: 292,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
}
}