//#382
export const thirdSome={
    	some_1: {type: 'BOOL',db: 119,dbb: 0,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_2: {type: 'BOOL',db: 119,dbb: 0,bit: 1,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_3: {type: 'BOOL',db: 119,dbb: 0,bit: 2,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_Int_1: {type: 'INT',db: 119,dbb: 2,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_0: {type: 'BOOL',db: 119,dbb: 4,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_byte_1: {type: 'BYTE',db: 119,dbb: 5,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit: {type: 'BOOL',db: 119,dbb: 6,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_real: {type: 'REAL',db: 119,dbb: 8,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_1: {type: 'BOOL',db: 119,dbb: 12,bit: 0,desc: 'some 1',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_real_2: {type: 'REAL',db: 119,dbb: 14,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_3: {type: 'BOOL',db: 119,dbb: 18,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_int: {type: 'INT',db: 119,dbb: 20,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	wasyl: {	some_1: {type: 'BOOL',db: 119,dbb: 22,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	int_1: {type: 'INT',db: 119,dbb: 24,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	some_4: {type: 'BOOL',db: 119,dbb: 26,bit: 0,desc: 'some 3',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	Other_Real: {type: 'REAL',db: 119,dbb: 28,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
some_arr: [
 {type: 'INT',db: 119,dbb: 32,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 34,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 36,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 38,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 40,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 42,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 44,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 46,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 48,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 50,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 52,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
 ],
	some_bool_2: {type: 'BOOL',db: 119,dbb: 54,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
some_other_arr: [
 {type: 'BOOL',db: 119,dbb: 56,bit: 0,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 1,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 2,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 3,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 4,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 5,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 6,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 56,bit: 7,desc: 'tekst some',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
 ],
	some_9_bool: {type: 'BOOL',db: 119,dbb: 58,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	other_Struct: {	one: {type: 'BOOL',db: 119,dbb: 60,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	two: {type: 'BOOL',db: 119,dbb: 60,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	three: {type: 'BOOL',db: 119,dbb: 60,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	some_other: {type: 'BOOL',db: 119,dbb: 62,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	r1: {type: 'BOOL',db: 119,dbb: 62,bit: 1,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bool_4: {type: 'BOOL',db: 119,dbb: 62,bit: 2,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_robert: {type: 'BOOL',db: 119,dbb: 62,bit: 3,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	other: {type: 'BOOL',db: 119,dbb: 62,bit: 4,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_Struct: {	rob: {type: 'BOOL',db: 119,dbb: 64,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	dipper_Struct: {	littleOne: {type: 'BOOL',db: 119,dbb: 66,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined},
	litttleTwo: {type: 'INT',db: 119,dbb: 68,bit: 0,desc: '',sD: 2,value: undefined,rOk: undefined,wOk: undefined}
}
},
	addidas: {type: 'BOOL',db: 119,dbb: 70,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	kot_1: {	item_1: {type: 'BOOL',db: 119,dbb: 72,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
	item_2: {type: 'BOOL',db: 119,dbb: 72,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
},
	byte_1: {type: 'BYTE',db: 119,dbb: 74,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_bit_2: {type: 'BOOL',db: 119,dbb: 75,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_byte: {type: 'BYTE',db: 119,dbb: 76,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	some_other_bit: {type: 'BOOL',db: 119,dbb: 77,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	char_1: {type: 'CHAR',db: 119,dbb: 78,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	bool_one: {type: 'BOOL',db: 119,dbb: 79,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	int_44: {type: 'INT',db: 119,dbb: 80,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sbool: {type: 'BOOL',db: 119,dbb: 82,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sReal: {type: 'REAL',db: 119,dbb: 84,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	ssbool: {type: 'BOOL',db: 119,dbb: 88,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	ssInt: {type: 'INT',db: 119,dbb: 90,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
ARR_Bool_11: [
 {type: 'BOOL',db: 119,dbb: 92,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 1,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 2,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 3,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 4,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 5,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 6,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 92,bit: 7,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'BOOL',db: 119,dbb: 93,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
 ],
	sssbool: {type: 'BOOL',db: 119,dbb: 94,bit: 1,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sssByte: {type: 'BYTE',db: 119,dbb: 95,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
	sssReal: {type: 'REAL',db: 119,dbb: 96,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined},
arr_big: [
 {type: 'INT',db: 119,dbb: 100,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 102,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 104,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 106,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 108,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 110,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 112,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 114,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 116,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 118,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 120,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined},
 {type: 'INT',db: 119,dbb: 122,bit: 0,desc: '',sD: 1,value: undefined,rOk: undefined,wOk: undefined}
 ],
	new_bool: {type: 'BOOL',db: 119,dbb: 124,bit: 0,desc: '',sD: 0,value: undefined,rOk: undefined,wOk: undefined}
}